server:
  port: 8082
spring:
  cloud:
    stream:
      bindings:
        output: 
          destination: election
          contentType: application/json
logging:
  level:
    com.netflix.discovery: 'OFF'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 10
