server:
  port: 8082
spring:
  cloud:
    stream:
      bindings:
        output: 
          destination: election
          contentType: application/json
logging:
  level:
    com.netflix.discovery: 'OFF'
  pattern:
    level: '%clr(%5p) %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow}'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 10
