server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: election
          content-type: application/x-java-object;type=demo.Vote
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
  pattern:
    level: '%clr(%5p) %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow}'
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 10
